name = "Streamator"
mainprefix = "tc"
modname = "Streamator"
prefix = ""
author = "Streamator Team"
sig_version = 3
version = "0.0.0"
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE"
]
include = ["./include"]

releasebuild = [
    "@zip @Streamator"
]

key_name = "Streamator_{{version}}"
authority = "Streamator_{{version}}-{{git \"id 8\"}}"

[header_exts]
version= "{{git \"id 8\"}}"
