name = "Streamator"
mainprefix = "tc"
modname = "Streamator"
prefix = ""
author = "Streamator Team"
sig_version = 3
version = "0.0.0"
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE"
]
include = ["./include"]

prebuild = [
    "!dev_set"
]

postbuild = [
    "!dev_unset"
]

releasebuild = [
    "@zip @Streamator"
]

key_name = "Streamator_{{version}}"
authority = "Streamator_{{version}}-{{git \"id 8\"}}"

[header_exts]
version= "{{git \"id 8\"}}"

[scripts.dev_set]
steps_linux = [
    "echo 'Setting Dev'",
    "sed -i -r -s 's/// #define ISDEV/ #define ISDEV {{semver.major}}/g' addons/Streamator/macros.hpp",
]
steps_windows = [
    "echo 'Setting Dev'",
    "powershell -Command foreach ($f in 'addons/Streamator/macros.hpp') {(Get-Content $f) -replace '// #define ISDEV', '#define ISDEV' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]
only_release = true
show_output = true

[scripts.dev_unset]
steps_linux = [
    "echo 'Unsetting Dev'",
    "sed -i -r -s 's/// #define ISDEV/#define ISDEV/g' addons/Streamator/macros.hpp",
]
steps_windows = [
    "echo 'Unsetting Dev'",
    "powershell -Command foreach ($f in 'addons/Streamator/macros.hpp') {(Get-Content $f) -replace '// #define ISDEV', '#define ISDEV' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]
only_release = true
show_output = true
